### ISSUE TITLE
(0 , _addYears.default) is not a function

### ISSUE THREAD

**Issue by semihraifgurel** [hypeserver/react-date-range#629]
## (0 , _addYears.default) is not a function
react-date-range not working with date-fns@3.0.1
 
## [BUG] Bug Reproduce Steps
[Codesandbox](https://codesandbox.io/p/sandbox/rdr-33nvd5?file=%2Fpackage.json%3A7%2C20)

## Environment
Package Version: 1.4.0
React version: 18.2.0
Node version:
Browser:

**Comment by semihraifgurel** [comment]
If you downgrade the version of date-fns to 2.30.0 it works.

**Comment by SyamsuddinNurSN** [comment]
in my project date-fns 2.30.0 still not works, Should react-date-range downgraded too?

**Comment by Tembew** [comment]
Been getting this past few days. Finally found that its an incompatibility with the newer date-fns. Probably because they use require("date-fns/addYears") instead of require("date-fns"). addYears is in the date-fns folder now instead of its own folder. same with other functions. Is it ok to break things like that? re date-fns devs.

**Comment by ty-codes** [comment]
Anybody have a solution yet?

**Comment by Aakashgupta2001** [comment]
> Anybody have a solution yet?

install version 2.30.0, then delete your node modules, install it again and it is working for me.

**Comment by ty-codes** [comment]
> > Anybody have a solution yet?
> 
> install date-fns version 2.30.0, then delete your node modules, install it again and it is working for me.

Thanks! It worked for me.

**Comment by umakantp** [comment]
Okay, I wanted to use the latest `date-fns` and this package was not compatible. I forked this repo and changed it to work with the latest `date-fns`. In case you want to use it: https://www.npmjs.com/package/@umakantp/react-date-range

**Comment by keremciu** [comment]
@semihraifgurel @Tembew @ty-codes @Aakashgupta2001 @umakantp 

can you please try latest version? https://www.npmjs.com/package/react-date-range/v/2.0.0-alpha.3 that should be working with date-fns@3

I'd like to make it an official release after we get enough feedback

**Comment by Tembew** [comment]
Seems to be working for what I needed it for.

**Comment by fbenfraj** [comment]
> @semihraifgurel @Tembew @ty-codes @Aakashgupta2001 @umakantp
> 
> can you please try latest version? https://www.npmjs.com/package/react-date-range/v/2.0.0-alpha.3 that should be working with date-fns@3
> 
> I'd like to make it an official release after we get enough feedback

Thank you so much!

**Comment by keremciu** [comment]
I just released version 2.0.1 @bensampaio @fbenfraj @Tembew

**Comment by MatheusFelipe1988** [comment]
> Se você fizer o downgrade da versão do date-fns para 2.30.0, ele funcionará.

working for me, ty

**Comment by nishchaya2k** [comment]
> install date-fns version 2.30.0, then delete your node modules, install it again and it is working for me.

Thank you!, it worked

**Comment by Chandankumarq** [comment]
> > Se você fizer o downgrade da versão do date-fns para 2.30.0, ele funcionará.
> 
> working for me, ty

????

**Comment by atillaertas1** [comment]
> > Anybody have a solution yet?
> 
> install date-fns version 2.30.0, then delete your node modules, install it again and it is working for me.

thx
